[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
